# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Ensemble_EN_Objective <- function(current_res, beta, lambda_sparsity, lambda_diversity, alpha) {
    .Call('_ensembleEN_Ensemble_EN_Objective', PACKAGE = 'ensembleEN', current_res, beta, lambda_sparsity, lambda_diversity, alpha)
}

Ensemble_EN_Grid <- function(x, y, which_lambda, lambdas_grid, lambda_fixed, alpha, num_groups, tolerance, max_iter) {
    .Call('_ensembleEN_Ensemble_EN_Grid', PACKAGE = 'ensembleEN', x, y, which_lambda, lambdas_grid, lambda_fixed, alpha, num_groups, tolerance, max_iter)
}

Main_Ensemble_EN <- function(x_perm, y_perm, num_lambdas_sparsity, num_lambdas_diversity, alpha, num_groups, tolerance, max_iter, num_folds, num_threads) {
    .Call('_ensembleEN_Main_Ensemble_EN', PACKAGE = 'ensembleEN', x_perm, y_perm, num_lambdas_sparsity, num_lambdas_diversity, alpha, num_groups, tolerance, max_iter, num_folds, num_threads)
}

